<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>HermitBook</title>
        <link rel="stylesheet" href="/static/style.css" />
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-177412705-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'UA-177412705-1');
        </script>

    </head>
    <body>
        <div id='wrap'>
            <div id='header'>
                <h1><a href='/'>HermitBook</a></h1>
                <ul id='menu'>
                    <li><a href='/'>Seasons</a>
                        <ul id="seasons" aria-label='submenu'></ul>
                    </li>
                    <li><a href='/about/'>About</a></li>
                    <li><a href='https://github.com/stevarino/hermit-book/issues'>Feedback</a></li>
                    <li><a href='https://github.com/stevarino/hermit-book'>Github</a></li>
                </ul>
            </div>
            <div id='content'>

