<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title><%= title %></title>
        <link rel="shortcut icon" href="/static/favicon.png"> 
        <link rel="stylesheet" href="/static/style.css?20210103.2" />
    </head>
    <body>
        <div id='wrap'>
            <div id='header'>
                <h1><a href='/'>Hermit<span
                    class='outline'><svg class='triangle' viewBox="0 0 100 100">
                        <polygon points="100,50 25,6.7 25,93.3" />
                    </svg><span>Tube</span></span></a></h1>
                <div class='menu-button'>
                    <div class="menu-icon">
                        <span class="line-1"></span>
                        <span class="line-2"></span>
                        <span class="line-3"></span>
                    </div>
                </div>
                <ul id='menu'>
                    <li><a href='#' onclick='return false' id='channel_dropdown'>Channels</a>
                    <ul id='channels' aria-label='submenu'></ul>
                </li>
                    <li><a ref='#' onclick='return false'>Seasons</a>
                        <ul id="seasons" aria-label='submenu'></ul>
                    </li>
                    <li><a href='#' onclick='return false'>Settings</a>
                        <ul id="settings" aria-label='submenu'>
                            <li><label for='opt_player'>
                                <input type='checkbox' id='opt_player' name='opt_player' />
                                Embedded Player Desktop
                            </label></li>
                            <li><label for='opt_player_mobile'>
                                <input type='checkbox' id='opt_player_mobile' name='opt_player_mobile' />
                                Embedded Player Mobile
                            </label></li>
                            <li><label for='opt_autoplay'>
                                <input type='checkbox' id='opt_autoplay' name='opt_autoplay' />
                                Autoplay next video
                            </label></li>
                            <li class='hr'></li>
                            <li><a href='#' id='profile_new'>New Profile</a></li>
                            <li><a href='#' id='profile_rename'>Rename Profile</a></li>
                            <li><a href='#' id='profile_delete'>Delete Profile</a></li>
                            <li class='hr' id='profile_sep'></li>
                        </ul>
                    </li>
                    <li><a href='/about/'>About</a></li>
                    <li><a href='https://github.com/stevarino/hermit-tube'>Github</a></li>
                </ul>
            </div>
            <div id='content'>

